// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GSW7DXVXQ2jeH65lThsrijbP1CcXHz0',
    appId: '1:1079524558162:web:9f1891349ca78bf4e0e68b',
    messagingSenderId: '1079524558162',
    projectId: 'notes-taking-app-afafa',
    authDomain: 'notes-taking-app-afafa.firebaseapp.com',
    storageBucket: 'notes-taking-app-afafa.appspot.com',
    measurementId: 'G-YBRKJJ0FX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYd2AeH9ug9nK4syBqM6yRH0WFP9s8Z4',
    appId: '1:1079524558162:android:fecf2cd1ce0338c8e0e68b',
    messagingSenderId: '1079524558162',
    projectId: 'notes-taking-app-afafa',
    storageBucket: 'notes-taking-app-afafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJmBc6Fzq4eLyQu8jR9wtiRcgwvlU3jz8',
    appId: '1:1079524558162:ios:962da5c3cc0615a2e0e68b',
    messagingSenderId: '1079524558162',
    projectId: 'notes-taking-app-afafa',
    storageBucket: 'notes-taking-app-afafa.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJmBc6Fzq4eLyQu8jR9wtiRcgwvlU3jz8',
    appId: '1:1079524558162:ios:962da5c3cc0615a2e0e68b',
    messagingSenderId: '1079524558162',
    projectId: 'notes-taking-app-afafa',
    storageBucket: 'notes-taking-app-afafa.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );
}
